# Site settings
url: "http://chadHarper.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "CH" # the name of your site, e.g. ACME Corp.
description: "Some web action. A little site situation."

#Exclusions
exclude:
  - courses 
  - people
  
# Collections
collections:
  writings:
    output: true
    permalink: /writings/:title
  fashion_criticism:
    output: true
    permalink: /fashion/criticism/:name/

# Plugins
plugins:
  - jekyll-paginate-v2

# Pagination settings
pagination:
  enabled: true
  collection: fashion_criticism
  per_page: 5
  permalink: '/fashion/criticism/page:num/'
