menu:
  - {name: 'writings', url: '/writings'}
  - {name: 'cv', url: '/cv'}
 # - {name: 'contact', url: '/contact'}

# Uncomment and update if you want to highlight specific writings
# writings:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
  - {icon: 'github', link: 'https://github.com/chadHarper'}
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/chad-harper-91b785b9/'}

# Uncomment if you want to use contacts on the contact page
# contacts:
# - {name: 'Your Name', title: 'Your Title', department: 'Your Department', institution: 'Your Institution', institution_address: 'Your Address', phone: 'Your Phone Number', email: 'Your Email', office: 'Your Office', image: 'path_to_image'}
